### ISSUE TITLE
Queue adapter/CPUs per task inconsistency

### ISSUE THREAD

**Issue by jmason42** [CovertLab/wcEcoli#192]
@tahorst noticed that my `my_qadapter.yaml` file i.e.

```yaml
logdir: /home/users/jmason42/fw/logs/qadapter
_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -w /scratch/users/jmason42/wcEcoli/wholecell/fireworks/my_fworker.yaml -l /scratch/users/jmason42/wcEcoli/my_launchpad.yaml singleshot
queue: mcovert
account: null
job_name: null
pre_rocket: null
post_rocket: null
ntasks: 1
cpus_per_node: 1
```

was setting the number of CPUs per node to 1 (as a default) when in reality it should be setting the number of CPUs per task i.e.

```yaml
logdir: /home/users/jmason42/fw/logs/qadapter
_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -w /scratch/users/jmason42/wcEcoli/wholecell/fireworks/my_fworker.yaml -l /scratch/users/jmason42/wcEcoli/my_launchpad.yaml singleshot
queue: mcovert
account: null
job_name: null
pre_rocket: null
post_rocket: null
ntasks: 1
cpus_per_task: 2
```

The former is how the template file is written, but I'm not even sure it makes sense to set `cpus_per_node`, and I think that conflicts with `cpus_per_task`.  So, the default file should be changed.

However - now I have tasks running with two CPUs instead of one, which should fix some of my problems, but confusingly the `cpus_per_task` setting in `my_qadapter.yaml` is overwriting any specific setting made by a task.  For example, even though I've started a workflow with `PARALLEL_FITTER=1`, which should run the fitter with 8 cores, I only received two:

```
        JOBID PARTITION                 NAME     USER    STATE       TIME NODELIST(REASON) CPUS
     20858114   mcovert               FW_job jmason42  RUNNING       8:07        sh-08-32    2
```

This is consistent with the submission script:

```bash
#!/bin/bash -l

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --partition=mcovert
#SBATCH --job-name=FW_job
#SBATCH --output=FW_job-%j.out
#SBATCH --error=FW_job-%j.error

cd /scratch/users/jmason42/wcEcoli/block_2018-06-27-22-10-10-207771/launcher_2018-06-28-22-24-47-324517
rlaunch -w /scratch/users/jmason42/wcEcoli/wholecell/fireworks/my_fworker.yaml -l /scratch/users/jmason42/wcEcoli/my_launchpad.yaml singleshot

# CommonAdapter (SLURM) completed writing Template
```

but not with the Fireworks task file

```json
{
    "name": "FitSimDataTask_Level_1", 
    "launches": [
        {
            "fworker": {
                "category": "", 
                "query": "{}", 
                "name": "default fireworker", 
                "env": {}
            }, 
            "trackers": [], 
            "ip": "10.10.8.32", 
            "fw_id": 10, 
            "state": "RUNNING", 
            "host": "sh-08-32.int", 
            "launch_dir": "/scratch/users/jmason42/wcEcoli/block_2018-06-27-22-10-10-207771/launcher_2018-06-28-22-24-47-324517", 
            "action": null, 
            "launch_id": 3, 
            "state_history": [
                {
                    "updated_on": "2018-06-28T22:25:12.079482", 
                    "state": "RUNNING", 
                    "created_on": "2018-06-28T22:25:12.079475"
                }
            ]
        }
    ], 
    "fw_id": 10, 
    "state": "RUNNING", 
    "created_on": "2018-06-28T22:19:12.238036", 
    "updated_on": "2018-06-28T22:25:12.160692", 
    "spec": {
        "_queueadapter": {
            "job_name": "FitSimDataTask_Level_1", 
            "cpus_per_task": 8
        }, 
        "_tasks": [
            {
                "disable_rnapoly_capacity_fitting": false, 
                "_fw_name": "{{wholecell.fireworks.firetasks.fitSimData.FitSimDataTask}}", 
                "cached_data": "/scratch/users/jmason42/wcEcoli/cached/simData_Fit_1.cPickle", 
                "cached": false, 
                "output_data": "/scratch/users/jmason42/wcEcoli/out/20180628.151910.563627__Both_fit/kb/simData_Fit_1.cPickle", 
                "cpus": 8, 
                "input_data": "/scratch/users/jmason42/wcEcoli/out/20180628.151910.563627__Both_fit/kb/rawData.cPickle", 
                "disable_ribosome_capacity_fitting": false, 
                "debug": false, 
                "fit_level": 1
            }
        ], 
        "_priority": 1
    }
}
```

and the `PARALLEL_FITTER` setting is definitely being passed to the Python script:

```
2018-06-28 15:25:02,135 INFO Hostname/IP lookup (this will take a few seconds)
2018-06-28 15:25:02,140 INFO Launching Rocket
2018-06-28 15:25:13,047 INFO RUNNING fw_id: 10 in directory: /scratch/users/jmason42/wcEcoli/block_2018-06-27-22-10-10-207771/launcher_2018-06-28-22-24-47-324517
2018-06-28 15:25:13,610 INFO Task started: {{wholecell.fireworks.firetasks.fitSimData.FitSimDataTask}}.
Thu Jun 28 15:25:13 2018: Creating/Fitting sim_data (Level 1)
Warning: running fitter in parallel with 8 processes - ensure there are enough cpus_per_task allocated
```

So I'm just not sure what the issue is here.  I'm also noticing that the job name isn't being passed - I end up with the default `--job-name=FW_job`.  Seems like the Firework spec is being created properly but it's not being used, or its being overwritten by the queue adapter.  Is anyone else having these issues?  Any guesses as to a solution?  I'm baffled, particularly if this is only an issue I have.  Apart from source-diving I'm not sure what I can do.
